apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coinbase-local.fullname" . }}
  labels:
    {{- include "coinbase-local.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "coinbase-local.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "coinbase-local.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "coinbase-local.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- $apiSecretName := required "values.apiSecretName must be set" .Values.apiSecretName }}
      {{- $configFile := default "app-config.toml" .Values.config.fileName }}
      {{- $configPath := printf "/app/config/%s" $configFile }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{- if .Values.image.tag }}{{ .Values.image.tag }}{{- else }}v{{ .Chart.AppVersion }}{{- end }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--config"
            - {{ $configPath | quote }}
          {{- range .Values.args }}
            - {{ . | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          volumeMounts:
            - name: app-config
              mountPath: /app/config
              readOnly: true
            - name: coinbase-secret
              mountPath: /app/secrets/coinbase
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: app-config
          configMap:
            name: {{ include "coinbase-local.fullname" . }}-config
            items:
              - key: {{ $configFile }}
                path: {{ $configFile }}
        - name: coinbase-secret
          secret:
            secretName: {{ $apiSecretName }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
